"""Initial schema

Revision ID: 019f8fb3410f
Revises: 93c97a9445fb
Create Date: 2026-07-16 01:10:39.622036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019f8fb3410f'
down_revision = '93c97a9445fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
