"""Initial schema

Revision ID: 20b14a5ec8fc
Revises: 019f8fb3410f
Create Date: 2026-07-16 01:26:59.009259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b14a5ec8fc'
down_revision = '019f8fb3410f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
