"""Initial schema

Revision ID: 93c97a9445fb
Revises: d908b1007f0d
Create Date: 2026-07-16 00:14:04.019730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c97a9445fb'
down_revision = 'd908b1007f0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
